package com.ipn.entidades;
// Generated 17/05/2014 12:39:02 AM by Hibernate Tools 3.6.0


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Archivo generated by hbm2java
 */
@Entity
@Table(name="archivo"
    ,catalog="wad_proyecto"
)
public class Archivo  implements java.io.Serializable {


     private Integer idarchivo;
     private Usuario usuario;
     private String nombreArchivo;
     private String tipoArchivo;
     private String size;
     private String path;

    public Archivo() {
    }

     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idarchivo", unique=true, nullable=false)
    public Integer getIdarchivo() {
        return this.idarchivo;
    }
    
    public void setIdarchivo(Integer idarchivo) {
        this.idarchivo = idarchivo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="usuario_idusuario",referencedColumnName = "idusuario", nullable=false)
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }

    
    @Column(name="nombreArchivo", nullable=false, length=70)
    public String getNombreArchivo() {
        return this.nombreArchivo;
    }
    
    public void setNombreArchivo(String nombreArchivo) {
        this.nombreArchivo = nombreArchivo;
    }

    
    @Column(name="tipoArchivo", nullable=false, length=10)
    public String getTipoArchivo() {
        return this.tipoArchivo;
    }
    
    public void setTipoArchivo(String tipoArchivo) {
        this.tipoArchivo = tipoArchivo;
    }

    
    @Column(name="size", nullable=false, length=45)
    public String getSize() {
        return this.size;
    }
    
    public void setSize(String size) {
        this.size = size;
    }

    
    @Column(name="path", nullable=false, length=100)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


